// <auto-generated />
namespace FirstABP.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class add_UserExtend : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(add_UserExtend));
        
        string IMigrationMetadata.Id
        {
            get { return "201711021312563_add_UserExtend"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
